### ISSUE TITLE
Refit and Rx

### ISSUE THREAD

**Issue by ararog** [paulcbetts/refit#109]
Can Refit be used with Rx?

**Comment by bennor** [comment]
Yeah mate. You just need to set the methods up to return `IObservable<Foo>` instead of `Task<Foo>`. See https://github.com/paulcbetts/refit#retrieving-the-response.

Also, observables are cold (i.e. do nothing until subscribed and issue a new request each time). See https://github.com/paulcbetts/refit/releases/tag/2.0.0 for more info.
