### ISSUE TITLE
Don't add a refitstubs if one isn't needed?

### ISSUE THREAD

**Issue by mburbea** [paulcbetts/refit#120]
Currently I have a project that takes a dependency on a package that uses refit. To work, I need to make refit's a dependency. When I install the package it automatically installs refit, which in turn adds a useless refitstubs.cs to my project. 

Is it possible to avoid generating a stub if you don't use refit's attributes?

**Comment by bennor** [comment]
This could be tricky because of the way Refit is installed via NuGet. 

@paulcbetts Could we look at splitting the NuGet into `Refit.Core` and `Refit.Generator` (or something with a less dumb name)? I think that would mean projects that depend on Refit would only need to depend on the core and wouldn't require the additional stuff the generator adds. Or am I missing something obvious?

**Comment by paulcbetts** [comment]
I'm not super excited about fixing this bug, it has no actual consequences other than to tweak developer OCD. Enhance Your Calm™ :smile_cat:

**Comment by bennor** [comment]
Hah, I figured you'd say something like that. :smile:

**Comment by luisrudge** [comment]
Well. It's not only OCD, but having a file that is auto generated inside my workspace and it's always auto generated with nothing. It's just useless. What's the best way to fix this?

**Comment by paulcbetts** [comment]
Wontfix unless someone can come up with a reason other than "it's annoying me on philosophical grounds"

**Comment by luisrudge** [comment]
I guess that inconsistent line endings popping up every now and then is more than "philosophical grounds"

**Comment by krishire** [comment]
Hi, 
I'm using Refit along with the MS Dynamics CRM Xrm Code base to create some custom activities accessing the external API etc. Since there is a restricting to use mutliple dlls in the CRM Area. I'm using the ILMerge executable to merge multiple dlls into one and here I'm struggling to take in the Stubs created, so please suggest me a way to stop creating this stubs or how to merge the stubs into the dlls.

**Comment by nikeee** [comment]
Deleting the generated RefitStubs will result in compilation errors although everything is fine since the RefitStubs isn't actually referenced in the parent project.
The best solution would actually be to split refit into multiple packages `Refit.Core` and `Refit.Generator` like @bennor suggested. Then it would be possible to use Refit.Generator as a development dependency only. And since everything is moving to be platform independent, it would at least make the generated API platform independent since there is no generator that depends on Windows (see #209).

**Comment by mbcrawfo** [comment]
> Wontfix unless someone can come up with a reason other than "it's annoying me on philosophical grounds"

I'm attempting to use refit in a Xamarin project that uses a PCL... and as far as I can tell this isn't (easily) possible because refitstubs requires System.Net.Http, which isn't available in PCLs.  As far as I can tell the only thing preventing this from being possible is the insistence on trying to compile refitstubs as soon refit is included. All I need in the PCL are the refit attributes to create the interface - I'm happy to do the instantiation in each platform specific project.

**Comment by Cheesebaron** [comment]
HttpClient **_is_** available in a PCL. You are simply using a profile such as one containing a target to Silverlight in some form.

Alternatively you can add the Microsoft HttpClient nuget and you have HttpClient available to you.

**Comment by mbcrawfo** [comment]
I would suggest adding a note about that - all of the (presumably outdated) top google results I found related to the issue indicated that the only way to get HttpClient in a PCL was to compile it yourself.
