### ISSUE TITLE
Cannot access to ApiException class.

### ISSUE THREAD

**Issue by aflorenzan** [paulcbetts/refit#126]
I want to catch an ApiException thrown, but I cannot access to the ApiException class to specify it in the catch clausure.

**Comment by bennor** [comment]
That's weird. It's public and not a nested class. Do you have a reference to and a `using` for `Refit`?

**Comment by aflorenzan** [comment]
I've the reference to `Refit` package in my project, also the `using` of the proper namespace.

Please check the image bellow:

![image](https://cloud.githubusercontent.com/assets/739610/5958633/efac5390-a79c-11e4-8804-5291ebb429e7.png)

**Comment by RTodorov** [comment]
Guys, AFAIK ApiException is platform specific. You can only use it on the Droid/Touch projects, not on the PCL (because of internal references to System.Net.Http.HttpResponseMessage).

I've made a wrapper to transport StatusCode + Content from ApiException to the PCL, but it's kinda ugly, maybe Paul can suggest a better solution.

**Comment by janniklind** [comment]
I am facing the same problem at the moment. It would be great, if ApiException was visible in the Core project (PCL). I do the following as a workaround until Refit.ApiException is visible in the PCL:

I create a custom HttpClientHandler and initialize the Refit RestService with it.

	public class ErrorHttpHandler : NativeMessageHandler /*HttpClientHandler*/ {

		protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) {

			HttpResponseMessage resp = await base.SendAsync(request, cancellationToken).ConfigureAwait(false);

			if (!resp.IsSuccessStatusCode) {
				throw await ApiException.Create (resp /*, settings*/);
			}

			return resp;

		}


	}

Then I have copied ApiException from the Refit source code and just put it directly in my own source code. Hence I get the same functionality and should be able to use the Refit.ApiException whenever it becomes visible in the PCL. Alternatively you could throw your own custom exceptions based on the HTTP status code and content of the response, instead of wrapping it in the generel ApiException.

@RTodorov I am able to use the System.Net.Http.HttpResponseMessage in my Xamarin Core project. (PCL), so what are the reasons that it cannot be used in the Refit PCL and at the same time let ApiException be visible in the Xamarin Core project?

@paulcbetts As an alternative to the ApiException, which is a general exception that you often catch and wrap anyway, I suggest a new feature. It would be great if one could add a custom error handler. Lets say with the interface.

IRefitErrorHandler:
bool CanHandleStatusCode(HttpStatusCode httpStatusCode)
void HandleResponse(HttpResponseMessage response, RefitSettings refitSettings = null)

The first method defines, if the given status code can be handled by the error handler, the second takes the response and refit settings, and generate a custom exception based on information in the response and finally throws the exception.

**Comment by bennor** [comment]
You guys are all overthinking this.

There is no technical reason why `ApiException` cannot be in the Portable library. It's simply not defined there at the moment. All we need to do is move it into the Portable library and you should be able to use it when you're building a PCL that depends on Refit.

@paulcbetts Would you prefer it to be in its own file, or is it cool just to chuck it in `RequestBuilder.cs`?

**Comment by janniklind** [comment]
Cool @bennor. Can this change already be downloaded in a nuget package now, or is it first in next release? and if in next release when is that coming?

**Comment by frankelydiaz** [comment]
When is gonna be published on nuget ?
