### ISSUE TITLE
You've somehow included the PCL version of Refit in your app. You need to use the platform-specific version!

### ISSUE THREAD

**Issue by PugnetGuillaume** [paulcbetts/refit#132]
I am referencing the refit nuget package from a pcl targeting Windows8 and Xamarin.iOS. I don't find any platform specific package of refit.
What is the correct way to use refit in a Xamarin PCL ?

**Comment by paulcbetts** [comment]
Include Refit in your app

**Comment by erickmendonca** [comment]
I had this same problem using Xamarin.Forms. The installation scripts is adding the necessary references on other projects?

**Comment by HassanJawed** [comment]
I have added this line in my first activity but still getting this error.
`using Refit;`

**Comment by Cheesebaron** [comment]
As the problem says, there are different versions of the DLL, they have the same name, but they each have different targets. Then one you have referenced seems to be the incorrect one.

**Comment by cfl777** [comment]
I have tried this in multiple ways:
-Different versions of refit tested (all the same versions used).
-Tried to setup the DI within the Setup.cs (android platform), instead of the a PCL. 
-I even tried to use a shared project instead of a PCL. Only xamarin android had refit installed - no logical way a PCL could break it, but still gave the same error..

**Comment by montecillodavidacn** [comment]
@paulcbetts 
Hi, I have use refit in my current project(Xamarin.MVVMCross) as I only want 1 source to access API then distribute it to the current platform. Is this possible? Please confirm.

So Im going to use the platform specific source code to access API using Refit under Android?
Kindly confirm on this?
