### ISSUE TITLE
boolean are always false

### ISSUE THREAD

**Issue by paddylov** [paulcbetts/refit#178]
Hi

When i call a service, all the boolean properties of the deserialised object are always false.
The json format is "property":true 

and my property is declare like this :

```
[JsonProperty ("property")]
public bool Property { get; set; }
```

but `Property` is always false. How can i fix it please?

**Comment by bennor** [comment]
First thing - you shouldn't need to worry about the casing: Json.NET (which we use for serialization) isn't case sensitive. So you shouldn't need `[JsonProperty("property")]` on a property named `Property`.

However, that isn't going to be causing your problem. Because we use Json.NET, it's very unlikely that the deserialization is failing - my guess is that the data you're getting back doesn't have the property in it. 

**Can you give us a more detailed example, or a repro project?**

**Comment by paddylov** [comment]
Hello Bennor,

Thx for the answer. you were right. It's was a mistake on my side. It works properly
