### ISSUE TITLE
Headers not sent after redirect

### ISSUE THREAD

**Issue by ncruces** [paulcbetts/refit#194]
I'm implementing the Eventbrite API in my app, and was faced with this issue:

```
    [Headers("Authorization: Bearer TOKEN")]
    public interface IEventbriteApi
    {
        [Get("/events/search")]
        Task<string> SearchEvents(string q);
    }
```

Because Eventbrite redirects `/events/search` to `/events/search/` (notice the additional slash), I kept getting a `401 Unauthorized`. I finally figured out that the `Authorization` header was being sent on the first request, but not on the second one. Adding the slash to `[Get("/events/search/")]` fixed it (in this case).

No idea if this is something Refit could handle?

**Comment by bennor** [comment]
That's the behaviour of the underlying `HttpClient` and it's done that way for security, so I'm not sure it's something we'd want to implement.

I'm not sure you can make the `HttpClient` retain the headers but you can tell it not to follow redirects (which would at least alert you to the correct error):

```csharp
var handler = new HttpClientHandler
{
    AutoFollowRedirects = false
};
var httpClient = new HttpClient(handler)
{ 
    BaseUri = new Uri("https://api.eventbrite.com") 
};
var api = RestService.For<IEventbriteApi>(client);
```

You might be able to write your own `HttpMessageHandler` to handle redirect the way you want, but it's likely to be a bit pointless because when APIs redirect, it's _usually_ due to you having the incorrect URL.

**Comment by ncruces** [comment]
OK, I see. I imagine there are some good reasons *not* to do this, then.

Disabling redirects is a good idea going forward. Thanks!
