### ISSUE TITLE
Strong named assembly?

### ISSUE THREAD

**Issue by malvinstn** [paulcbetts/refit#297]
Hi, Is it possible to have Refit to be signed?
Or do I need to use `ildasm` `ilasm` to sign using my own key?

**Comment by Cheesebaron** [comment]
Your best bet is to sign it yourself.

**Comment by FroggieFrog** [comment]
Maybe this tool can help: [StrongNamer](https://www.nuget.org/packages/StrongNamer/)

**Comment by Cheesebaron** [comment]
Brutal Dev Strong Name tool works.

**Comment by zeelux** [comment]
For anyone else who stumbles onto this... I ran into this issue this week in my first foray into Refit. In my project I am required to use strong named assemblies. When importing through nuget everything is working until runtime where I get the error that it is not strong named. 

I came across this issue and found that if I remove the nuget package and reference the refit.dll (that I signed myself using ildasm/ilasm) directly I am then presented with a different runtime error. This time the issue comes from inside Refit where it cannot find the autogenerated classes that implement your interface. The nuget package sets up these build steps for you but if you're not using the nuget package, you don't get these automatically.

I'm using an older build (2.4.1) due to my own dependency on JSON.Net 9.0 so maybe this is resolved in newer versions but if not, I'd love to see Refit include a strong named assembly.

I was able to work around this by copying the build targets and the refit InterfaceStubGenerator.exe from the nuget packages folder into my project and adding the reference directly in my csproj. But it would be great if it just worked out of the box for strong named projects.
