### ISSUE TITLE
Error After Adding Refit on RefitStubs.g.cs (WinForms .Net 4.5 Application)

### ISSUE THREAD

**Issue by jmro20** [paulcbetts/refit#314]
I have a WinForms .net 4.5 Application and when I add the Refit nuget the application won't compile because of errors in the RefitStubs.g.cs file. This project references a PCL project which is the one that contains all the Refit code, but that project does compile without any issue.

![capture](https://cloud.githubusercontent.com/assets/11727609/26381184/e1410226-3ff0-11e7-8759-427a32e057f7.PNG)

**Comment by Cheesebaron** [comment]
Is this a VB.Net Application?

**Comment by onovotny** [comment]
Unfortunately, Refit does not currently support VB.Net due to lack of demand. We might consider a PR though if someone wants to add a compatible generator file for it, and changes in the cmd line to invoke it:
https://github.com/paulcbetts/refit/blob/master/InterfaceStubGenerator/GeneratedInterfaceStubTemplate.mustache

**Comment by jmro20** [comment]
Yes it is a VB.Net Application. That's the problem!
